sudo: required
dist: trusty
language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
#  - clang


git:
  depth: 1

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    sudo apt-get -qq update;
    sudo apt-get -qq install zlib1g-dev libssl-dev libpcre3-dev libbz2-dev libmysqlclient-dev libmysql++-dev;
    fi
# don not use gcc, gcc will redirected to llvm anyway
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew update;
    brew install mysql openssl pcre lbzip2;
    fi

install:
  - mkdir ascemu_build
  - cd ascemu_build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=1


before_script:
  - ${CXX} --version
  - ${CC} --version
  - cmake --version
